#   Configure file for pyklockAuto 
#   (c) Kevin Scott   Written Tuesday 19 May 2026  21:00:07
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2026.3"
myNAME = "pyklockAuto"

[APPLICATION]
x_pos = 100
y_pos = 100
width = 800
height = 600
confirmExit = false
style = "MaterialDark.qss"
