#   Configure file for pyklockAuto 
#   (c) Kevin Scott   Written Thursday 28 May 2026  16:38:01
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2026.6"
myNAME = "pyklockAuto"

[APPLICATION]
x_pos = 100
y_pos = 100
width = 800
height = 600
confirmExit = false
style = "MaterialDark.qss"
